travis:
  secure:
    BINSTAR_TOKEN: F9FEqZO2qcV+0Is27MX53ctrwnScjUO8NE94NhcqsRci79SH5iYWfTbsPHd3yfOuKmwMeOz3z8YSKrudkOkXvyF84ySGVVUlxH3uqmdnYXVgYZN8ehnYPWrzfG1GwxXc42IGTJEJ5/jfyaZQxZC433CDKH7dZ2Set2i/hFeNx4eGKVe6DdJdOq9xoStT3gj2oII5bUmovvGaBqMjtC3GnDGBuBaw+IfSmwkkNR12qMKaELGRZeATC8NH/9Zz65xLohnyNtrq1gHf0m6vDBOr32Jej0su+Hn0talVwxtL3YBaN7wp5wDb89NmbzcAgPg1DFDSMhTq+WgHg8kf+nN4MTZEvW6C6aW0bnpITO5ro1e22HNfaF4XP/XUBC6v+34O+q8BC3JVlBLwb3drmjXAs7mjOdcHkmZY4SHZEC26Z5+KyBpgidW7okds2tEKOaRp1JUc7b648h/vyXwqCSKDYrouve9VJPcNtEDjMksS6VX05y/709BeYDefXe18WGk7bjcVM+1xieGEGWKJOAs3LJAtmvKan5pkw0flizFKxxNiXqnf8nx7v1ipjQaBI3IBikNwv4GyW+mb4MTOWSd3rd1C5BebebNz3LMAvafijZAhAFXfSiazQWnFSsN0cqq62XKfqzBAU2gVu2zmIWyxbTTbfJt97SUxsWxOI6SwNCE=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
