travis:
  secure:
    BINSTAR_TOKEN: slGkndgZmhN2JPu59IH4arWKUu3UNXJj0Mi7jA/Jlkd9HnO8nE1LZ2vVJHoX262IMr5ue1ldeh3MDUeep6+NlCrOqdzHBpHywAt+1HkT87D/pWIjeJEp4yh+sWGP0L6W/zF86FK/REhkTcM83iW/FXVcEKZWN1KcO1Wd8+h08v6pA3vN3BBo6E7k1/AhDaqG4z0mnCe6zlC4Kbv26EBJd2vqW6zz/7fkgFV0z6I/GcAJ7wGiZb/+x9y+4BvRN8WLGTlawkj5XrQZlDGcHwuJXI63ovnH8pWsk31MYbhxDg7KmLxgrd+POdAEseNLyaePFn9/gXu6BcP30bUa0NN2XaUVK8fjW4D9qXOXxTGipnhPYYqyQUO8FKnHuELqZWvMeIKiJnwHCZe1DSx+hcmExZmHR16CQs36W1A0WQbqAxpWAr8oMuF0XuoaT17k7aaWWRmCHiu6rupAl3dIgmYJAFJcGKIjIOGEbqoX/RoJHVELrGMOQt5g5RowKkJsDOCcrqloDtSDKcVQVAoIOeBgKS47JIMuCx0LHxxpjmGAf8vqp0VQqVzCTN+ZxhodLt90pVisvjpuAxvgSRuqnrLHg3Y/8/hVsQ0QwvBwpftlMSqA0jEsjEI/B9PxLmfgNR2VRjofTRCDgQWelZjKoW4YYPJzrGm3tuoWzX4HXuS1JdY=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
